version: '2'

networks:
  app-tier:
    driver: bridge

services:
  phpfpm:
    build: .
    container_name: phpfpm
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - .:/app
      - ./php.ini:/opt/bitnami/php/etc/conf.d/custom.ini
    expose:
      - 9003

  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./server.conf:/opt/bitnami/nginx/conf/server_blocks/server.conf
      - .:/app

  mysql:
    image: 'bitnami/mysql:latest'
    depends_on:
      - nginx
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_CHARACTER_SET=utf8mb
      - MYSQL_COLLATE=utf8mb4_unicode_ci
      - MYSQL_USER=app
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - app-tier
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/bitnami/mysql/data
      - ./mysql.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
